/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorArduino;
import Controlador.ControladorPersona;
import Controlador.ControladorRiego;
import Modelo.Persona;
import java.awt.Desktop;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author VINICIO
 */
public class PrincipalUsuario extends javax.swing.JFrame {

    private UsuariosDatos ventanaUsuarios;
    private boolean bandera = true;
    private ControladorArduino arduino;
    private Programar ventanaProgramar;
    private VentanaRiego ventanaRiengoUsr;
    private ControladorRiego controladorRiego;
    private ControladorPersona controladorPersona;
    private Persona p;
    private String cedula;
    
    
    private ListaDatosUsuario ventanaListaDatosUsuario;
    public PrincipalUsuario() {
        int n;
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        ventanaRiengoUsr = new VentanaRiego(btnDRiegos, arduino);
        ventanaListaDatosUsuario = new ListaDatosUsuario(btnLista, p);
        escritorio.setFocusable(false);
        controladorRiego = new ControladorRiego();
        controladorPersona = new ControladorPersona();
        arduino = new ControladorArduino();
        JOptionPane.showMessageDialog(this, "Pas o no pasa");
    }
    
    public PrincipalUsuario(String cedula) {
         int n;
        initComponents();
        this.cedula = cedula;
        this.setExtendedState(MAXIMIZED_BOTH);
        controladorRiego = new ControladorRiego();
        controladorPersona = new ControladorPersona();
        this.p = controladorPersona.findByCedula(cedula);
        JOptionPane.showMessageDialog(this, p.getNombre());
        arduino = new ControladorArduino(p);
        ventanaListaDatosUsuario = new ListaDatosUsuario(btnLista, this.p);
        arduino.conectar();
        
        ventanaRiengoUsr = new VentanaRiego(btnDRiegos, arduino);
        escritorio.setFocusable(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        salir = new javax.swing.JButton();
        btnDRiegos = new javax.swing.JButton();
        btnLista = new javax.swing.JButton();
        btnRiego = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/login.png"))); // NOI18N
        salir.setText("LOGIN");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        btnDRiegos.setText("MI RIEGO");
        btnDRiegos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDRiegosActionPerformed(evt);
            }
        });

        btnLista.setText("LISTA DE RIEGOS / TABULACION");
        btnLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaActionPerformed(evt);
            }
        });

        btnRiego.setText("RIEGO");
        btnRiego.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRiego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRiegoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(1070, 1070, 1070)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(btnDRiegos, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLista, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
            .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(escritorioLayout.createSequentialGroup()
                    .addGap(531, 531, 531)
                    .addComponent(btnRiego, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(532, Short.MAX_VALUE)))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDRiegos, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLista, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(241, 241, 241)
                .addComponent(salir))
            .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(escritorioLayout.createSequentialGroup()
                    .addGap(226, 226, 226)
                    .addComponent(btnRiego, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(226, Short.MAX_VALUE)))
        );
        escritorio.setLayer(salir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(btnDRiegos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(btnLista, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(btnRiego, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(escritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        arduino.desconetar();
        Login vu = new Login();
        String[] args = null;
        vu.main(args);
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void btnDRiegosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDRiegosActionPerformed
        if (ventanaRiengoUsr.isShowing() != true) {
            ventanaRiengoUsr = new VentanaRiego(btnDRiegos, arduino);
            btnDRiegos.setEnabled(false);
            escritorio.add(ventanaRiengoUsr);
            ventanaRiengoUsr.setVisible(true);
        }
    }//GEN-LAST:event_btnDRiegosActionPerformed

    private void btnListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaActionPerformed
        if (ventanaListaDatosUsuario.isShowing() != true) {
            ventanaListaDatosUsuario = new ListaDatosUsuario(btnLista, this.p);
            JOptionPane.showMessageDialog(this, this.p.getNombre()+" >>>>>>>>>>");
            btnLista.setEnabled(false);
            escritorio.add(ventanaListaDatosUsuario);
            ventanaListaDatosUsuario.setVisible(true);
        }
    }//GEN-LAST:event_btnListaActionPerformed

    private void btnRiegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRiegoActionPerformed
        if (btnRiego.isSelected()) {
            btnRiego.setText("OFF");
            arduino.enviarDatos("1");
        } else {
            arduino.enviarDatos("2");
            btnRiego.setText("ON");
        }
    }//GEN-LAST:event_btnRiegoActionPerformed

    @Override
    protected void finalize() throws Throwable {
        System.out.println("finalzado");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new PrincipalUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDRiegos;
    private javax.swing.JButton btnLista;
    private javax.swing.JToggleButton btnRiego;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables

}
